# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rockets.ui'
#
# Created: Fri Aug  8 01:57:43 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Rockets(object):
    def setupUi(self, Rockets):
        Rockets.setObjectName(_fromUtf8("Rockets"))
        Rockets.resize(360, 472)
        Rockets.setMinimumSize(QtCore.QSize(360, 472))
        Rockets.setMaximumSize(QtCore.QSize(360, 472))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon/Objects-Rocket-icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Rockets.setWindowIcon(icon)
        Rockets.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(Rockets)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 341, 401))
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Burntime_tab = QtGui.QWidget()
        self.Burntime_tab.setAccessibleName(_fromUtf8(""))
        self.Burntime_tab.setObjectName(_fromUtf8("Burntime_tab"))
        self.burntime2output = QtGui.QLabel(self.Burntime_tab)
        self.burntime2output.setGeometry(QtCore.QRect(70, 280, 201, 21))
        self.burntime2output.setBaseSize(QtCore.QSize(0, 0))
        self.burntime2output.setAcceptDrops(False)
        self.burntime2output.setFrameShape(QtGui.QFrame.Box)
        self.burntime2output.setFrameShadow(QtGui.QFrame.Sunken)
        self.burntime2output.setLineWidth(1)
        self.burntime2output.setText(_fromUtf8(""))
        self.burntime2output.setObjectName(_fromUtf8("burntime2output"))
        self.label_4 = QtGui.QLabel(self.Burntime_tab)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 201, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.requiredv = QtGui.QLineEdit(self.Burntime_tab)
        self.requiredv.setGeometry(QtCore.QRect(70, 40, 201, 20))
        self.requiredv.setObjectName(_fromUtf8("requiredv"))
        self.label_3 = QtGui.QLabel(self.Burntime_tab)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 201, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.burntimeoutput = QtGui.QLabel(self.Burntime_tab)
        self.burntimeoutput.setGeometry(QtCore.QRect(70, 240, 201, 21))
        self.burntimeoutput.setBaseSize(QtCore.QSize(0, 0))
        self.burntimeoutput.setAcceptDrops(False)
        self.burntimeoutput.setStyleSheet(_fromUtf8("gridline-color: rgb(255, 255, 127);"))
        self.burntimeoutput.setFrameShape(QtGui.QFrame.Box)
        self.burntimeoutput.setFrameShadow(QtGui.QFrame.Sunken)
        self.burntimeoutput.setLineWidth(1)
        self.burntimeoutput.setText(_fromUtf8(""))
        self.burntimeoutput.setObjectName(_fromUtf8("burntimeoutput"))
        self.label_2 = QtGui.QLabel(self.Burntime_tab)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 201, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.totalthrust = QtGui.QLineEdit(self.Burntime_tab)
        self.totalthrust.setGeometry(QtCore.QRect(70, 190, 201, 20))
        self.totalthrust.setObjectName(_fromUtf8("totalthrust"))
        self.label_5 = QtGui.QLabel(self.Burntime_tab)
        self.label_5.setGeometry(QtCore.QRect(70, 220, 201, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_1 = QtGui.QLabel(self.Burntime_tab)
        self.label_1.setGeometry(QtCore.QRect(70, 20, 201, 16))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.currentmass = QtGui.QLineEdit(self.Burntime_tab)
        self.currentmass.setGeometry(QtCore.QRect(70, 140, 201, 20))
        self.currentmass.setObjectName(_fromUtf8("currentmass"))
        self.isp = QtGui.QLineEdit(self.Burntime_tab)
        self.isp.setGeometry(QtCore.QRect(70, 90, 201, 20))
        self.isp.setObjectName(_fromUtf8("isp"))
        self.tabWidget.addTab(self.Burntime_tab, _fromUtf8(""))
        self.deltaV_tab = QtGui.QWidget()
        self.deltaV_tab.setObjectName(_fromUtf8("deltaV_tab"))
        self.deltaVoutput = QtGui.QLabel(self.deltaV_tab)
        self.deltaVoutput.setGeometry(QtCore.QRect(70, 190, 201, 21))
        self.deltaVoutput.setBaseSize(QtCore.QSize(0, 0))
        self.deltaVoutput.setAcceptDrops(False)
        self.deltaVoutput.setFrameShape(QtGui.QFrame.Box)
        self.deltaVoutput.setFrameShadow(QtGui.QFrame.Sunken)
        self.deltaVoutput.setLineWidth(1)
        self.deltaVoutput.setText(_fromUtf8(""))
        self.deltaVoutput.setObjectName(_fromUtf8("deltaVoutput"))
        self.label = QtGui.QLabel(self.deltaV_tab)
        self.label.setGeometry(QtCore.QRect(70, 20, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.isp_2 = QtGui.QLineEdit(self.deltaV_tab)
        self.isp_2.setGeometry(QtCore.QRect(70, 40, 201, 20))
        self.isp_2.setObjectName(_fromUtf8("isp_2"))
        self.label_6 = QtGui.QLabel(self.deltaV_tab)
        self.label_6.setGeometry(QtCore.QRect(70, 120, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.deltaV_tab)
        self.label_7.setGeometry(QtCore.QRect(70, 70, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.deltaV_tab)
        self.label_8.setGeometry(QtCore.QRect(70, 170, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.init_mass = QtGui.QLineEdit(self.deltaV_tab)
        self.init_mass.setGeometry(QtCore.QRect(70, 90, 201, 20))
        self.init_mass.setObjectName(_fromUtf8("init_mass"))
        self.final_mass = QtGui.QLineEdit(self.deltaV_tab)
        self.final_mass.setGeometry(QtCore.QRect(70, 140, 201, 20))
        self.final_mass.setObjectName(_fromUtf8("final_mass"))
        self.tabWidget.addTab(self.deltaV_tab, _fromUtf8(""))
        self.exit_button = QtGui.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(192, 370, 81, 23))
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.calculate_button = QtGui.QPushButton(self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(92, 370, 81, 23))
        self.calculate_button.setObjectName(_fromUtf8("calculate_button"))
        Rockets.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Rockets)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Rockets.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Rockets)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Rockets.setStatusBar(self.statusbar)

        self.retranslateUi(Rockets)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Rockets)

    def retranslateUi(self, Rockets):
        Rockets.setWindowTitle(_translate("Rockets", "Rockets", None))
        self.label_4.setText(_translate("Rockets", "Total Thrust", None))
        self.label_3.setText(_translate("Rockets", "Current Mass", None))
        self.label_2.setText(_translate("Rockets", "Isp", None))
        self.label_5.setText(_translate("Rockets", "Burntime", None))
        self.label_1.setText(_translate("Rockets", "Required dV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Burntime_tab), _translate("Rockets", "Burntime", None))
        self.label.setText(_translate("Rockets", "Isp in seconds", None))
        self.label_6.setText(_translate("Rockets", "Final Mass", None))
        self.label_7.setText(_translate("Rockets", "Initial Mass", None))
        self.label_8.setText(_translate("Rockets", "ΔV in m/s", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deltaV_tab), _translate("Rockets", "DeltaV", None))
        self.exit_button.setText(_translate("Rockets", "Beenden", None))
        self.calculate_button.setText(_translate("Rockets", "Calculate", None))

